### ISSUE TITLE
importing OrderedDict from typing breaks doltpy on Python 3.6

### ISSUE THREAD

**Issue by AmirAktify** [dolthub/doltpy#131]
This is because `doltpy/types/dolt.py`  imports `OrderedDict` from typing, and it was only added in Python 3.7. I was able to get this to work locally by monkey-patching / editing that import out of the file.

Admittedly, 3.6 is a somewhat older version....... but its not something as ancient as Python2, and Python 3.6 is still default on Ubuntu 18.04.

**Comment by oscarbatori** [comment]
@AmirAktify - thanks for flagging this, we will figure something out. We should work with 3.6 seamlessly, I am sorry you encountered this.

@max-hoffman any thoughts on what we should do here?

**Comment by max-hoffman** [comment]
this will add python 3.6 support https://github.com/dolthub/doltpy/pull/130

**Comment by oscarbatori** [comment]
This has been resolved.
