### ISSUE TITLE
Documentation for syncing between other databases and Dolt seems to be out of date

### ISSUE THREAD

**Issue by evanirla** [dolthub/doltpy#138]
The sync documentation linked in the readme looks to be out of date. Some examples:

 - doltpy.core does not exist
 - function names and locations of those function names do not always match. (Like where is ‘sql_server()’?)

**Comment by oscarbatori** [comment]
Thanks for flagging this, we did indeed make breaking changes that were not reflected in the docs. This has been fixed and deployed.
